[mypy]
ignore_missing_imports = True
check_untyped_defs = True
disable_error_code =
    arg-type,
    assignment,
    attr-defined,
    call-overload,
    has-type,
    index,
    misc,
    no-redef,
    operator,
    override,
    return,
    return-value,
    type-arg,
    union-attr,
    var-annotated

[mypy-custom_components.loxone.pyloxone_api.*]
follow_imports = silent
ignore_errors = True
